# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterator_rcpp <- function(Rg, f_T, f_VPD, GPP_c, LAI_c, k, epsilon_max) {
    .Call(`_BioSim_iterator_rcpp`, Rg, f_T, f_VPD, GPP_c, LAI_c, k, epsilon_max)
}

LAI_model_rcpp <- function(Tavg, VPD, Rg, TMIN, TMAX, VPD_MIN, VPD_MAX, epsilon_max, k, GPP_c, LAI_c, LAI_min, W, n_smooth) {
    .Call(`_BioSim_LAI_model_rcpp`, Tavg, VPD, Rg, TMIN, TMAX, VPD_MIN, VPD_MAX, epsilon_max, k, GPP_c, LAI_c, LAI_min, W, n_smooth)
}

